FROM fedora:44

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN dnf install -y python3 python3-pip curl ca-certificates vulkan-loader vulkan-tools libglvnd libglvnd-glx libglvnd-egl libXext libXrender libXrandr \
    && python3 -m pip install --upgrade pip \
    && python3 -m pip install litert-lm \
    && dnf clean all

WORKDIR /models

ENTRYPOINT ["litert-lm"]
